# Setup
title:               Cloud Equivalence
description:         'A comparision tool for cloud practicioners.'
paginate:            5
permalink:           pretty

# GitHub
domain:              mikail-khan.github.io
url:                 https://mikail-khan.github.io

# About/contact
author:
  name:              Mikail Khan
  url:               https://github.com/mikail-khan/mikail-khan.github.io
  email:             mikail.dev.io@gmail.com

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
